export declare function getSegmentPaths(segments: any): any;
export declare function getAllSegments(segments: any): any[];
export declare function getIntersectionId(rowPath: any, columnPath: any): string;
export declare function findSegment(segments: any, id: any): unknown;
export declare function canSummarizeSegment(segments: any, id: any): boolean;
export declare function summarizeSegment(design: any, id: any, label: any): any;
export declare function replaceSegment(segments: any, replacement: any): unknown[];
export declare function removeSegment(segments: any, id: any): unknown[];
export declare function insertBeforeSegment(segments: any, id: any): unknown[];
export declare function insertAfterSegment(segments: any, id: any): unknown[];
export declare function addChildSegment(segments: any, id: any): unknown[];
