"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UtfGridLayer = exports.BingLayer = void 0;
var LeafletMapComponent_1 = require("./maps/LeafletMapComponent");
Object.defineProperty(exports, "LeafletMapComponent", { enumerable: true, get: function () { return LeafletMapComponent_1.default; } });
var DateRangeComponent_1 = require("./DateRangeComponent");
Object.defineProperty(exports, "DateRangeComponent", { enumerable: true, get: function () { return DateRangeComponent_1.default; } });
var RegionSelectComponent_1 = require("./maps/RegionSelectComponent");
Object.defineProperty(exports, "RegionSelectComponent", { enumerable: true, get: function () { return RegionSelectComponent_1.default; } });
__exportStar(require("./datagrids/DatagridDesign"), exports);
var TableSelectComponent_1 = require("./TableSelectComponent");
Object.defineProperty(exports, "TableSelectComponent", { enumerable: true, get: function () { return TableSelectComponent_1.default; } });
__exportStar(require("./JsonQLFilter"), exports);
var DashboardComponent_1 = require("./dashboards/DashboardComponent");
Object.defineProperty(exports, "DashboardComponent", { enumerable: true, get: function () { return DashboardComponent_1.default; } });
var DashboardDataSource_1 = require("./dashboards/DashboardDataSource");
Object.defineProperty(exports, "DashboardDataSource", { enumerable: true, get: function () { return DashboardDataSource_1.default; } });
var DirectDashboardDataSource_1 = require("./dashboards/DirectDashboardDataSource");
Object.defineProperty(exports, "DirectDashboardDataSource", { enumerable: true, get: function () { return DirectDashboardDataSource_1.default; } });
__exportStar(require("./dashboards/DashboardDesign"), exports);
var compressJson_1 = require("./compressJson");
Object.defineProperty(exports, "compressJson", { enumerable: true, get: function () { return compressJson_1.default; } });
var LocaleContextInjector_1 = require("./LocaleContextInjector");
Object.defineProperty(exports, "LocaleContextInjector", { enumerable: true, get: function () { return LocaleContextInjector_1.default; } });
__exportStar(require("./WidgetScope"), exports);
var WidgetFactory_1 = require("./widgets/WidgetFactory");
Object.defineProperty(exports, "WidgetFactory", { enumerable: true, get: function () { return WidgetFactory_1.default; } });
var Widget_1 = require("./widgets/Widget");
Object.defineProperty(exports, "Widget", { enumerable: true, get: function () { return Widget_1.default; } });
var DatagridUtils_1 = require("./datagrids/DatagridUtils");
Object.defineProperty(exports, "DatagridUtils", { enumerable: true, get: function () { return DatagridUtils_1.default; } });
__exportStar(require("./maps/MapViewComponent"), exports);
var MWaterLoaderComponent_1 = require("./MWaterLoaderComponent");
Object.defineProperty(exports, "MWaterLoaderComponent", { enumerable: true, get: function () { return MWaterLoaderComponent_1.default; } });
var MWaterContextComponent_1 = require("./MWaterContextComponent");
Object.defineProperty(exports, "MWaterContextComponent", { enumerable: true, get: function () { return MWaterContextComponent_1.default; } });
var mWaterLoader_1 = require("./mWaterLoader");
Object.defineProperty(exports, "mWaterLoader", { enumerable: true, get: function () { return mWaterLoader_1.default; } });
var DirectWidgetDataSource_1 = require("./widgets/DirectWidgetDataSource");
Object.defineProperty(exports, "DirectWidgetDataSource", { enumerable: true, get: function () { return DirectWidgetDataSource_1.default; } });
require("leaflet/dist/leaflet.css");
require("fixed-data-table-2/dist/fixed-data-table.min.css");
require("rc-slider/assets/index.css");
require("./layouts/decorated-block.css");
require("react-datepicker/dist/react-datepicker.css");
require("c3/c3.css");
require("./index.css");
var CachingDataSource_1 = require("./CachingDataSource");
Object.defineProperty(exports, "CachingDataSource", { enumerable: true, get: function () { return CachingDataSource_1.default; } });
var UndoStack_1 = require("./UndoStack");
Object.defineProperty(exports, "UndoStack", { enumerable: true, get: function () { return UndoStack_1.default; } });
var DashboardViewComponent_1 = require("./dashboards/DashboardViewComponent");
Object.defineProperty(exports, "DashboardViewComponent", { enumerable: true, get: function () { return DashboardViewComponent_1.default; } });
exports.BingLayer = require("./maps/BingLayer");
exports.UtfGridLayer = require("./maps/UtfGridLayer");
var LayerFactory_1 = require("./maps/LayerFactory");
Object.defineProperty(exports, "LayerFactory", { enumerable: true, get: function () { return LayerFactory_1.default; } });
var MapDesignerComponent_1 = require("./maps/MapDesignerComponent");
Object.defineProperty(exports, "MapDesignerComponent", { enumerable: true, get: function () { return MapDesignerComponent_1.default; } });
var MapComponent_1 = require("./maps/MapComponent");
Object.defineProperty(exports, "MapComponent", { enumerable: true, get: function () { return MapComponent_1.default; } });
var VerticalLayoutComponent_1 = require("./VerticalLayoutComponent");
Object.defineProperty(exports, "VerticalLayoutComponent", { enumerable: true, get: function () { return VerticalLayoutComponent_1.default; } });
var RadioButtonComponent_1 = require("./RadioButtonComponent");
Object.defineProperty(exports, "RadioButtonComponent", { enumerable: true, get: function () { return RadioButtonComponent_1.default; } });
var CheckboxComponent_1 = require("./CheckboxComponent");
Object.defineProperty(exports, "CheckboxComponent", { enumerable: true, get: function () { return CheckboxComponent_1.default; } });
var LayeredChart_1 = require("./widgets/charts/layered/LayeredChart");
Object.defineProperty(exports, "LayeredChart", { enumerable: true, get: function () { return LayeredChart_1.default; } });
var TableChart_1 = require("./widgets/charts/table/TableChart");
Object.defineProperty(exports, "TableChart", { enumerable: true, get: function () { return TableChart_1.default; } });
var CalendarChart_1 = require("./widgets/charts/calendar/CalendarChart");
Object.defineProperty(exports, "CalendarChart", { enumerable: true, get: function () { return CalendarChart_1.default; } });
var ImageMosaicChart_1 = require("./widgets/charts/imagemosaic/ImageMosaicChart");
Object.defineProperty(exports, "ImageMosaicChart", { enumerable: true, get: function () { return ImageMosaicChart_1.default; } });
var ChartViewComponent_1 = require("./widgets/charts/ChartViewComponent");
Object.defineProperty(exports, "ChartViewComponent", { enumerable: true, get: function () { return ChartViewComponent_1.default; } });
var WidgetScoper_1 = require("./widgets/WidgetScoper");
Object.defineProperty(exports, "WidgetScoper", { enumerable: true, get: function () { return WidgetScoper_1.default; } });
var WidgetScopesViewComponent_1 = require("./widgets/WidgetScopesViewComponent");
Object.defineProperty(exports, "WidgetScopesViewComponent", { enumerable: true, get: function () { return WidgetScopesViewComponent_1.default; } });
var AxisBuilder_1 = require("./axes/AxisBuilder");
Object.defineProperty(exports, "AxisBuilder", { enumerable: true, get: function () { return AxisBuilder_1.default; } });
var ColorSchemeFactory_1 = require("./ColorSchemeFactory");
Object.defineProperty(exports, "ColorSchemeFactory", { enumerable: true, get: function () { return ColorSchemeFactory_1.default; } });
var DatagridComponent_1 = require("./datagrids/DatagridComponent");
Object.defineProperty(exports, "DatagridComponent", { enumerable: true, get: function () { return DatagridComponent_1.default; } });
var DatagridViewComponent_1 = require("./datagrids/DatagridViewComponent");
Object.defineProperty(exports, "DatagridViewComponent", { enumerable: true, get: function () { return DatagridViewComponent_1.default; } });
var ServerDashboardDataSource_1 = require("./dashboards/ServerDashboardDataSource");
Object.defineProperty(exports, "ServerDashboardDataSource", { enumerable: true, get: function () { return ServerDashboardDataSource_1.default; } });
var ServerMapDataSource_1 = require("./maps/ServerMapDataSource");
Object.defineProperty(exports, "ServerMapDataSource", { enumerable: true, get: function () { return ServerMapDataSource_1.default; } });
var DirectMapDataSource_1 = require("./maps/DirectMapDataSource");
Object.defineProperty(exports, "DirectMapDataSource", { enumerable: true, get: function () { return DirectMapDataSource_1.default; } });
var ServerDatagridDataSource_1 = require("./datagrids/ServerDatagridDataSource");
Object.defineProperty(exports, "ServerDatagridDataSource", { enumerable: true, get: function () { return ServerDatagridDataSource_1.default; } });
var DirectDatagridDataSource_1 = require("./datagrids/DirectDatagridDataSource");
Object.defineProperty(exports, "DirectDatagridDataSource", { enumerable: true, get: function () { return DirectDatagridDataSource_1.default; } });
var LabeledExprGenerator_1 = require("./datagrids/LabeledExprGenerator");
Object.defineProperty(exports, "LabeledExprGenerator", { enumerable: true, get: function () { return LabeledExprGenerator_1.default; } });
var LayoutManager_1 = require("./layouts/LayoutManager");
Object.defineProperty(exports, "LayoutManager", { enumerable: true, get: function () { return LayoutManager_1.default; } });
var DetailLevelSelectComponent_1 = require("./maps/DetailLevelSelectComponent");
Object.defineProperty(exports, "DetailLevelSelectComponent", { enumerable: true, get: function () { return DetailLevelSelectComponent_1.default; } });
var MarkerSymbolSelectComponent_1 = require("./maps/MarkerSymbolSelectComponent");
Object.defineProperty(exports, "MarkerSymbolSelectComponent", { enumerable: true, get: function () { return MarkerSymbolSelectComponent_1.default; } });
var AxisColorEditorComponent_1 = require("./axes/AxisColorEditorComponent");
Object.defineProperty(exports, "AxisColorEditorComponent", { enumerable: true, get: function () { return AxisColorEditorComponent_1.default; } });
var RichTextComponent_1 = require("./richtext/RichTextComponent");
Object.defineProperty(exports, "RichTextComponent", { enumerable: true, get: function () { return RichTextComponent_1.default; } });
var ItemsHtmlConverter_1 = require("./richtext/ItemsHtmlConverter");
Object.defineProperty(exports, "ItemsHtmlConverter", { enumerable: true, get: function () { return ItemsHtmlConverter_1.default; } });
var DropdownWidgetComponent_1 = require("./widgets/DropdownWidgetComponent");
Object.defineProperty(exports, "DropdownWidgetComponent", { enumerable: true, get: function () { return DropdownWidgetComponent_1.default; } });
var QuickfilterCompiler_1 = require("./quickfilter/QuickfilterCompiler");
Object.defineProperty(exports, "QuickfilterCompiler", { enumerable: true, get: function () { return QuickfilterCompiler_1.default; } });
// Polyfill pathseg https://github.com/masayuki0812/c3/issues/1529
require("./pathseg-polyfill");
// http://stackoverflow.com/questions/19305821/multiple-modals-overlay
const jquery_1 = __importDefault(require("jquery"));
jquery_1.default(document).on("show.bs.modal", ".modal", function () {
    const zIndex = 1040 + 10 * jquery_1.default(".modal:visible").length;
    jquery_1.default(this).css("z-index", zIndex);
    setTimeout(function () {
        jquery_1.default(".modal-backdrop")
            .not(".modal-stack")
            .css("z-index", zIndex - 1)
            .addClass("modal-stack");
    }, 0);
});
jquery_1.default(document).on("hidden.bs.modal", ".modal", function () {
    jquery_1.default(".modal:visible").length && jquery_1.default(document.body).addClass("modal-open");
});
